# Generated by Django 5.0.4 on 2024-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebooks", "0002_alter_review_review_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
